//go:build integration
// +build integration

// activity_seq_backfill_integration_test.go — REAL Postgres proof of the
// invariant the 20260604000000_activity_logs_seq.up.sql migration guarantees:
// every activity_logs row carries a NON-NULL `seq`, both for rows that existed
// before the migration ran (assigned during the ALTER TABLE rewrite) and for
// rows created afterward via the normal INSERT path (assigned by the IDENTITY
// default). This is the coverage CR2 (#2339 review) correctly flagged as
// missing on PR #2258.
//
// WHY THIS IS A SEPARATE TEST from activity_since_id_ordering_integration_test.go:
// that test pins the *ordering* contract (same-microsecond rows come back in a
// deterministic (created_at, seq) order). THIS test pins the *backfill* contract
// — that `seq` is never NULL — and the consequence the reviewer doubted: a
// pre-existing/backfilled row is usable as a since_id cursor because its seq is
// non-null, so the tuple cursor `(created_at, seq)` the handler builds is well
// defined for it.
//
// EMPIRICAL BASIS (PostgreSQL 16.13, the prod PG version):
//   - `ALTER TABLE activity_logs ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS
//     IDENTITY` rewrites the table and assigns seq to EXISTING rows in physical
//     table-scan order — they are NON-NULL, not left NULL as the review claimed.
//   - The identity sequence then advances ABOVE max(seq), so the next INSERT
//     that omits seq gets max+1 with no collision.
// Run against any Postgres 15/16 the integration harness boots — the property
// holds on both.
//
// Run with (same harness as activity_delegation_a2a_integration_test.go):
//
//	docker run --rm -d --name pg-integration \
//	  -e POSTGRES_PASSWORD=test -e POSTGRES_DB=molecule \
//	  -p 55432:5432 postgres:15-alpine
//	sleep 4
//	# apply migrations (incl. 20260604000000_activity_logs_seq.up.sql) then:
//	INTEGRATION_DB_URL="postgres://postgres:test@localhost:55432/molecule?sslmode=disable" \
//	  go test -tags=integration ./internal/handlers/ -run Integration_ActivityLogs_Seq
//
// WATCH-IT-FAIL: if `seq` were left nullable / un-backfilled (the failure mode
// the reviewer hypothesized), the NULL-count assertion in _NoNull trips, and
// the since_id-on-a-backfilled-row case in _SinceIDOnBackfilledRow trips because
// the handler cannot read a non-null seq for the cursor row. With the migration
// as written both are green every run.

package handlers

import (
	"context"
	"encoding/json"
	"net/http"
	"testing"
	"time"

	"git.moleculesai.app/molecule-ai/molecule-core/workspace-server/internal/db"
	"github.com/gin-gonic/gin"
)

// TestIntegration_ActivityLogs_SeqBackfill_NoNull pins the core migration
// invariant: AFTER migrations have run, NO activity_logs row may have a NULL
// seq — neither rows that the seedActivityRowAt path inserts (IDENTITY default)
// nor any row the schema carries. It also proves the IDENTITY sequence keeps
// producing distinct, non-null seq for fresh inserts (no collision, no NULL).
//
// This is the assertion that would FAIL if the ALTER had left existing rows
// with NULL seq (the reviewer's claim) — table-scan backfill makes it pass.
func TestIntegration_ActivityLogs_SeqBackfill_NoNull(t *testing.T) {
	conn := integrationDB_ActivityDelegationA2A(t)
	_ = conn
	wsID := seedWorkspace(t, conn, "test-2151-seq-backfill-nonull")

	// Insert several rows via the normal path. seq is left to the IDENTITY
	// default — exactly how production writes activity_logs.
	t0 := time.Date(2026, 6, 4, 9, 0, 0, 0, time.UTC)
	const n = 5
	ids := make([]string, 0, n)
	for i := 0; i < n; i++ {
		ids = append(ids, seedActivityRowAt(t, wsID, "backfill-row", t0.Add(time.Duration(i)*time.Second)))
	}

	// (a) No row in this workspace may have a NULL seq. If the column were
	// un-backfilled / nullable this is > 0 and the test fails.
	var nullCount int
	if err := db.DB.QueryRowContext(context.Background(),
		`SELECT COUNT(*) FROM activity_logs WHERE workspace_id = $1 AND seq IS NULL`,
		wsID,
	).Scan(&nullCount); err != nil {
		t.Fatalf("null-seq count query: %v", err)
	}
	if nullCount != 0 {
		t.Fatalf("found %d activity_logs rows with NULL seq — migration did NOT backfill/assign seq", nullCount)
	}

	// Belt-and-suspenders: the GLOBAL invariant (no NULL seq anywhere in the
	// table) is what the migration actually guarantees. Assert it too, so a
	// regression that nulls seq for rows written by some other path is caught.
	var globalNull int
	if err := db.DB.QueryRowContext(context.Background(),
		`SELECT COUNT(*) FROM activity_logs WHERE seq IS NULL`,
	).Scan(&globalNull); err != nil {
		t.Fatalf("global null-seq count query: %v", err)
	}
	if globalNull != 0 {
		t.Fatalf("found %d activity_logs rows table-wide with NULL seq — seq must be non-null for every row", globalNull)
	}

	// (b) The IDENTITY sequence yields DISTINCT, monotonic, non-null seq for
	// the rows we just inserted (proves the normal insert path gets a real seq,
	// and that the sequence advanced past any backfilled max instead of
	// colliding). We read them back in insert order and require strictly
	// increasing, all-non-null seq.
	rows, err := db.DB.QueryContext(context.Background(),
		`SELECT seq FROM activity_logs WHERE workspace_id = $1 ORDER BY created_at ASC, seq ASC`,
		wsID,
	)
	if err != nil {
		t.Fatalf("read-back seq query: %v", err)
	}
	defer rows.Close()
	var seqs []int64
	for rows.Next() {
		var s *int64 // pointer so a NULL would scan as nil rather than 0
		if err := rows.Scan(&s); err != nil {
			t.Fatalf("scan seq: %v", err)
		}
		if s == nil {
			t.Fatal("a freshly-inserted activity_logs row has NULL seq — IDENTITY default did not fire")
		}
		seqs = append(seqs, *s)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows err: %v", err)
	}
	if len(seqs) != n {
		t.Fatalf("expected %d rows, read back %d", n, len(seqs))
	}
	for i := 1; i < len(seqs); i++ {
		if seqs[i] <= seqs[i-1] {
			t.Fatalf("seq not strictly increasing in insert order: %v (IDENTITY collision / reuse)", seqs)
		}
	}
}

// TestIntegration_ActivityLogs_SeqBackfill_SinceIDOnBackfilledRow pins the
// consequence the reviewer doubted: a row whose seq came from the migration /
// IDENTITY (i.e. NOT explicitly set by the caller) is usable as a since_id
// cursor, and a SECOND row sharing its exact created_at microsecond is returned
// (not dropped). This proves the handler's (created_at, seq) tuple cursor
// resolves a same-timestamp boundary that a created_at-only cursor would drop,
// AND that the cursor row's seq is non-null (else the handler could not build
// the tuple at all).
//
// Distinct from _BoundaryRowSameMicrosecondNotSkipped in the ordering test:
// here the explicit angle under test is "the cursor row's seq is a
// migration/IDENTITY-assigned (backfilled-style) value, non-null, and the
// handler uses it" — i.e. the backfill behavior is what makes the boundary
// resolution work, pinned head-on.
func TestIntegration_ActivityLogs_SeqBackfill_SinceIDOnBackfilledRow(t *testing.T) {
	conn := integrationDB_ActivityDelegationA2A(t)
	_ = conn
	wsID := seedWorkspace(t, conn, "test-2151-seq-backfill-sinceid")

	tSame := time.Date(2026, 6, 4, 10, 0, 0, 0, time.UTC)
	// Cursor row: seq comes purely from the IDENTITY default (never set by
	// the caller) — the same assignment mechanism the migration uses to
	// backfill pre-existing rows. The "next" row shares the exact created_at
	// microsecond and is inserted afterward, so it gets a strictly higher seq.
	cursorID := seedActivityRowAt(t, wsID, "sinceid-cursor", tSame)
	nextID := seedActivityRowAt(t, wsID, "sinceid-next-same-us", tSame)

	// Prove the precondition the reviewer doubted: the cursor row's seq is
	// NON-NULL, so the handler can read it to build the (created_at, seq)
	// tuple. If it were NULL the handler's cursor lookup would yield a NULL
	// seq and the strictly-after tuple comparison would mis-behave.
	var cursorSeq *int64
	if err := db.DB.QueryRowContext(context.Background(),
		`SELECT seq FROM activity_logs WHERE id = $1`, cursorID,
	).Scan(&cursorSeq); err != nil {
		t.Fatalf("read cursor seq: %v", err)
	}
	if cursorSeq == nil {
		t.Fatal("cursor row has NULL seq — a since_id cursor on a backfilled-style row would be unusable")
	}

	h := NewActivityHandler(nil)
	c, w := newTestGinContext()
	c.Params = gin.Params{{Key: "id", Value: wsID}}
	q := c.Request.URL.Query()
	q.Set("since_id", cursorID)
	q.Set("type", "a2a_receive")
	q.Set("limit", "10")
	c.Request.URL.RawQuery = q.Encode()

	h.List(c)
	if w.Code != http.StatusOK {
		t.Fatalf("List returned %d, want 200: %s", w.Code, w.Body.String())
	}
	var resp []map[string]interface{}
	if err := json.Unmarshal(w.Body.Bytes(), &resp); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	// Exactly the one same-microsecond row after the cursor — present (not
	// dropped by a strict created_at-only filter) and the cursor itself
	// excluded (strictly-after on the full tuple).
	if len(resp) != 1 {
		t.Fatalf("same-microsecond row after backfilled-style cursor dropped: expected 1 row, got %d: %+v",
			len(resp), resp)
	}
	if got, _ := resp[0]["id"].(string); got != nextID {
		t.Fatalf("expected boundary row id %s, got %s", nextID, got)
	}
}
