//go:build integration
// +build integration

// inbox_delivery_ack_integration_test.go — REAL Postgres integration tests
// for MUST-FIX 3 (durable acked delivery + conservative prune) and the
// MUST-FIX 4 durable fix (FAILED branch emits a delegate_result row).
//
// Run with:
//
//	docker run --rm -d --name pg-integration \
//	  -e POSTGRES_PASSWORD=test -e POSTGRES_DB=molecule \
//	  -p 55432:5432 postgres:15-alpine
//	sleep 4
//	# apply migrations (boot runner or psql loop), then:
//	cd workspace-server
//	INTEGRATION_DB_URL="postgres://postgres:test@localhost:55432/molecule?sslmode=disable" \
//	  go test -tags=integration ./internal/handlers/ -run Integration_InboxAck -run Integration_Prune -run Integration_UpdateStatusFailed
//
// Why these are NOT plain sqlmock unit tests: sqlmock can pin which SQL
// fires but cannot execute the predicate, so it cannot prove that the prune
// actually RETAINS an old-but-unacked row, or that GREATEST actually keeps
// the higher cursor across two POSTs. These boot a real Postgres and SELECT
// the resulting row state.

package handlers

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"testing"
	"time"

	mdb "git.moleculesai.app/molecule-ai/molecule-core/workspace-server/internal/db"
	_ "github.com/lib/pq"
)

// integrationDB_InboxAck opens $INTEGRATION_DB_URL, wipes this test's
// namespace (workspaces named test-mf3-%, cascading to activity_logs +
// inbox_delivery_state), hot-swaps the package-level db.DB, and restores it
// on Cleanup. NOT SAFE FOR t.Parallel().
func integrationDB_InboxAck(t *testing.T) *sql.DB {
	t.Helper()
	url := os.Getenv("INTEGRATION_DB_URL")
	if url == "" {
		t.Fatal("INTEGRATION_DB_URL not set; failing (local devs: see file header)")
	}
	conn, err := sql.Open("postgres", url)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := conn.PingContext(ctx); err != nil {
		t.Fatalf("ping: %v", err)
	}
	cleanup := func() {
		if _, err := conn.ExecContext(context.Background(), `
			DELETE FROM inbox_delivery_state WHERE workspace_id IN (SELECT id FROM workspaces WHERE name LIKE 'test-mf3-%');
			DELETE FROM activity_logs WHERE workspace_id IN (SELECT id FROM workspaces WHERE name LIKE 'test-mf3-%');
			DELETE FROM workspaces WHERE name LIKE 'test-mf3-%';
		`); err != nil {
			t.Fatalf("cleanup: %v", err)
		}
	}
	cleanup()
	prev := mdb.DB
	mdb.DB = conn
	t.Cleanup(func() {
		cleanup()
		mdb.DB = prev
		conn.Close()
	})
	return conn
}

// insertAgedActivity inserts an activity_logs row with an explicit seq and a
// created_at set ageDays in the past. seq is GENERATED BY DEFAULT so an
// explicit value is accepted; tests own all their seq values.
func insertAgedActivity(t *testing.T, conn *sql.DB, wsID string, seq int64, ageDays int) {
	t.Helper()
	if _, err := conn.ExecContext(context.Background(), `
		INSERT INTO activity_logs (workspace_id, activity_type, status, seq, created_at)
		VALUES ($1, 'agent_log', 'ok', $2, now() - make_interval(days => $3::int))
	`, wsID, seq, ageDays); err != nil {
		t.Fatalf("insertAgedActivity seq=%d: %v", seq, err)
	}
}

func activitySeqExists(t *testing.T, conn *sql.DB, wsID string, seq int64) bool {
	t.Helper()
	var exists bool
	if err := conn.QueryRowContext(context.Background(),
		`SELECT EXISTS(SELECT 1 FROM activity_logs WHERE workspace_id=$1 AND seq=$2)`, wsID, seq).Scan(&exists); err != nil {
		t.Fatalf("activitySeqExists seq=%d: %v", seq, err)
	}
	return exists
}

// TestIntegration_PruneKeepsUnackedRows is the defining behavioural contract
// for MUST-FIX 3: the prune reclaims old rows ONLY once acked, keeps
// old-but-unacked rows below the hard ceiling, and the hard ceiling is the
// unconditional backstop. Strictly more conservative than the old age-only
// prune (which would have deleted every old row regardless of ack).
func TestIntegration_PruneKeepsUnackedRows(t *testing.T) {
	conn := integrationDB_InboxAck(t)

	wsA := seedWorkspace(t, conn, "test-mf3-prune-a")
	insertAgedActivity(t, conn, wsA, 1001, 10) // old, will be acked -> DELETE
	insertAgedActivity(t, conn, wsA, 1002, 10) // old, unacked          -> KEEP
	insertAgedActivity(t, conn, wsA, 1003, 1)  // fresh                 -> KEEP
	insertAgedActivity(t, conn, wsA, 1004, 40) // ancient, unacked      -> DELETE (hard)
	if _, err := conn.ExecContext(context.Background(),
		`INSERT INTO inbox_delivery_state (workspace_id, last_acked_seq) VALUES ($1, 1001)`, wsA); err != nil {
		t.Fatalf("seed cursor: %v", err)
	}

	// wsB has NO cursor row: COALESCE(...,0) means nothing is acked, so an
	// old-but-unacked row must survive the soft floor; only the hard ceiling
	// reclaims its ancient row.
	wsB := seedWorkspace(t, conn, "test-mf3-prune-b")
	insertAgedActivity(t, conn, wsB, 2001, 10) // old, no cursor   -> KEEP
	insertAgedActivity(t, conn, wsB, 2002, 40) // ancient          -> DELETE (hard)

	n, err := mdb.PruneActivityLogs(context.Background(), 7, 30)
	if err != nil {
		t.Fatalf("PruneActivityLogs: %v", err)
	}
	if n < 3 {
		t.Fatalf("expected at least 3 rows pruned (1001,1004,2002), got %d", n)
	}

	gone := func(ws string, seq int64) {
		if activitySeqExists(t, conn, ws, seq) {
			t.Errorf("seq %d should have been pruned but survived", seq)
		}
	}
	kept := func(ws string, seq int64) {
		if !activitySeqExists(t, conn, ws, seq) {
			t.Errorf("seq %d should have been KEPT but was pruned", seq)
		}
	}
	gone(wsA, 1001) // old + acked
	kept(wsA, 1002) // old + unacked  (the whole point of MUST-FIX 3)
	kept(wsA, 1003) // fresh
	gone(wsA, 1004) // ancient (hard ceiling)
	kept(wsB, 2001) // old + no cursor -> treated as unacked
	gone(wsB, 2002) // ancient (hard ceiling)
}

// TestIntegration_InboxAck_MonotonicMaxAdvance drives the real Ack handler and
// asserts the durable cursor only ever advances (GREATEST), is idempotent,
// and a stale lower ack is a no-op.
func TestIntegration_InboxAck_MonotonicMaxAdvance(t *testing.T) {
	conn := integrationDB_InboxAck(t)
	ws := seedWorkspace(t, conn, "test-mf3-ack")
	h := NewActivityHandler(noOpEmitter{})

	post := func(seq int64) int64 {
		c, w := postAck(ws, fmt.Sprintf(`{"acked_seq": %d}`, seq))
		h.Ack(c)
		if w.Code != http.StatusOK {
			t.Fatalf("Ack(%d) -> %d: %s", seq, w.Code, w.Body.String())
		}
		return decodeAckSeq(t, w)
	}

	if got := post(5); got != 5 {
		t.Fatalf("after ack 5: cursor=%d want 5", got)
	}
	if got := post(3); got != 5 {
		t.Fatalf("after STALE ack 3: cursor=%d want 5 (monotonic, must not regress)", got)
	}
	if got := post(10); got != 10 {
		t.Fatalf("after ack 10: cursor=%d want 10", got)
	}
	if got := post(10); got != 10 {
		t.Fatalf("idempotent re-ack 10: cursor=%d want 10", got)
	}

	var stored int64
	if err := conn.QueryRowContext(context.Background(),
		`SELECT last_acked_seq FROM inbox_delivery_state WHERE workspace_id=$1`, ws).Scan(&stored); err != nil {
		t.Fatalf("read durable cursor: %v", err)
	}
	if stored != 10 {
		t.Fatalf("durable cursor=%d want 10", stored)
	}
}

// TestIntegration_UpdateStatusFailed_EmitsDelegateResult proves the MUST-FIX 4
// durable fix: an agent-reported FAILED status writes exactly one
// delegate_result activity row (status 'failed', error in error_detail) with
// both the ledger and inbox-push flags off — so the runtime harvester needs
// no status-flip workaround.
func TestIntegration_UpdateStatusFailed_EmitsDelegateResult(t *testing.T) {
	conn := integrationDB_InboxAck(t)
	ws := seedWorkspace(t, conn, "test-mf3-deleg-failed")
	const delID = "del-mf3-failed"

	taskJSON, _ := json.Marshal(map[string]interface{}{"task": "x", "delegation_id": delID})
	if _, err := conn.ExecContext(context.Background(), `
		INSERT INTO activity_logs (workspace_id, activity_type, method, source_id, target_id, summary, request_body, status)
		VALUES ($1, 'delegation', 'delegate', $1, $1, 'Delegating', $2::jsonb, 'dispatched')
	`, ws, string(taskJSON)); err != nil {
		t.Fatalf("seed delegate row: %v", err)
	}

	h := NewDelegationHandler(&WorkspaceHandler{broadcaster: noOpEmitter{}}, noOpEmitter{})
	c, w := postDelegationUpdate(ws, delID, `{"status":"failed","error":"kaboom"}`)
	h.UpdateStatus(c)
	if w.Code != http.StatusOK {
		t.Fatalf("UpdateStatus(failed) -> %d: %s", w.Code, w.Body.String())
	}

	var cnt int
	var errDetail sql.NullString
	if err := conn.QueryRowContext(context.Background(), `
		SELECT count(*), max(error_detail)
		FROM activity_logs
		WHERE workspace_id=$1 AND method='delegate_result' AND status='failed'
	`, ws).Scan(&cnt, &errDetail); err != nil {
		t.Fatalf("query delegate_result: %v", err)
	}
	if cnt != 1 {
		t.Fatalf("expected exactly 1 failed delegate_result row, got %d", cnt)
	}
	if errDetail.String != "kaboom" {
		t.Fatalf("delegate_result error_detail=%q want kaboom", errDetail.String)
	}
}
