package handlers

// M6 / FIX 1 + FIX 2: an org node's `template:` supplies the BASE config.
//
// Today `ensureDefaultConfig` generates config.yaml purely from the org node's
// own fields (runtime, model, tier). The referenced workspace template's
// config.yaml is used only to COPY files — its content is dropped. So an org
// node written as
//
//	- name: SEO
//	  template: seo-agent
//
// gets none of that template's `providers` registry, `models[]`, `env`,
// `skills`, `a2a` or `runtime_config`. Those keys exist ONLY in the template,
// which is the whole reason a node references one.
//
// This merges the template config as the base and overlays the generated config
// on top, so node-owned identity wins and template-only keys survive.
//
// FIX 2 — the overlay is gated on an EXPLICIT `template:`. A node without one
// keeps today's behaviour byte-for-byte, which is what makes this safe to land
// on a path that provisions whole orgs.

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// templateBaseExcludedKeys are keys a referenced template may NOT supply.
//
// `model` and `provider` are deliberately excluded. The SSOT rule (CTO
// 2026-05-22, and the note carried in every bundled template) is that a model is
// REQUIRED user input and a template must never re-pin it — an empty model is a
// visible not_configured, whereas a template-supplied one is a silent
// substitution of somebody else's choice. `name` is excluded because the org
// node names the workspace; inheriting the template's catalog name would
// rename every node that references it.
var templateBaseExcludedKeys = map[string]bool{
	"model":    true,
	"provider": true,
	"name":     true,
}

// mergeTemplateConfigBase overlays a generated config.yaml onto a template's.
//
// Precedence: generated (org node) wins per top-level key, EXCEPT that an
// absent-or-empty generated value does not erase a template value — an empty
// string in the generated config means "the node did not say", not "set this to
// empty". Template-only keys (providers, models, env, skills, …) survive
// untouched, which is the point.
//
// Shallow by design. A deep merge would silently interleave two authors' intent
// inside `runtime_config` or `providers`, and a half-merged provider registry is
// far worse to debug than a wholly-replaced one.
func mergeTemplateConfigBase(templateYAML, generatedYAML []byte) ([]byte, error) {
	var base map[string]any
	if err := yaml.Unmarshal(templateYAML, &base); err != nil {
		return nil, fmt.Errorf("parse template config.yaml: %w", err)
	}
	var gen map[string]any
	if err := yaml.Unmarshal(generatedYAML, &gen); err != nil {
		return nil, fmt.Errorf("parse generated config.yaml: %w", err)
	}
	if base == nil {
		// Nothing to inherit — hand back the generated bytes unchanged rather
		// than re-marshalling them, so formatting is untouched.
		return generatedYAML, nil
	}
	if gen == nil {
		gen = map[string]any{}
	}

	out := make(map[string]any, len(base)+len(gen))
	for k, v := range base {
		if templateBaseExcludedKeys[k] {
			continue
		}
		out[k] = v
	}
	for k, v := range gen {
		if isEmptyConfigValue(v) {
			// The node did not say. Keep whatever the template had — unless the
			// key is excluded, in which case it was never copied in and this
			// correctly leaves it absent.
			if _, inherited := out[k]; inherited {
				continue
			}
		}
		out[k] = v
	}

	merged, err := yaml.Marshal(out)
	if err != nil {
		return nil, fmt.Errorf("render merged config.yaml: %w", err)
	}
	return merged, nil
}

// isEmptyConfigValue reports whether a generated value carries no information.
// Zero numbers are NOT empty — `tier: 0` is a real (if unusual) choice, and
// treating it as absent would silently promote a template's tier.
func isEmptyConfigValue(v any) bool {
	switch t := v.(type) {
	case nil:
		return true
	case string:
		return t == ""
	default:
		return false
	}
}

// templateDeclaredPlugins reads the `plugins:` a workspace template declares.
//
// M6 / FIX 3. Today `mergePlugins(defaults.Plugins, ws.Plugins)` unions the ORG
// DEFAULTS with the NODE's own list and never looks at the template a node
// references — so an org node written as
//
//   - name: SEO
//     template: seo-agent
//
// does not get seo-agent's own declared plugins (seo-all and friends). The
// template is the thing that knows which plugins its agent needs; the node
// referenced it precisely to avoid restating them.
//
// Entries are source-contract strings, the same shape `plugins:` already uses
// everywhere else (`gitea://owner/repo#ref` or a bare local name). Both the
// bare-string and the {source, config} object forms are accepted, because a
// template that sets per-install config (sdk#176) writes the object form.
//
// Tolerant: a malformed or absent block yields no plugins rather than an error.
// A template that cannot be parsed must not fail an org import — the node still
// provisions, just without inherited plugins.
func templateDeclaredPlugins(templateYAML []byte) []string {
	var doc struct {
		Plugins []yaml.Node `yaml:"plugins"`
	}
	if err := yaml.Unmarshal(templateYAML, &doc); err != nil {
		return nil
	}
	out := make([]string, 0, len(doc.Plugins))
	for _, n := range doc.Plugins {
		var s string
		if err := n.Decode(&s); err == nil {
			if s = strings.TrimSpace(s); s != "" {
				out = append(out, s)
			}
			continue
		}
		var obj struct {
			Source string `yaml:"source"`
		}
		if err := n.Decode(&obj); err == nil {
			if src := strings.TrimSpace(obj.Source); src != "" {
				out = append(out, src)
			}
		}
	}
	return out
}

// mergePluginsWithTemplate is the three-layer plugin precedence for a node that
// references a template: TEMPLATE, then org DEFAULTS, then the NODE.
//
// It delegates to the existing mergePlugins so the opt-out grammar is shared
// rather than reimplemented — a node can still drop an inherited plugin with a
// leading "!" or "-", including one that came from the template. That matters:
// inheriting a template's plugins is only safe if a node can decline one.
func mergePluginsWithTemplate(templatePlugins, defaultPlugins, wsPlugins []string) []string {
	return mergePlugins(mergePlugins(templatePlugins, defaultPlugins), wsPlugins)
}
