package handlers

// M6 done condition, at the merge level: an org node with `template: seo-agent`
// gets that template's providers registry and models[].
//
// Driven by the REAL key shapes bundled templates use — providers,
// runtime_config, models, env, skills, a2a — not invented ones.

import (
	"testing"

	"gopkg.in/yaml.v3"
)

// The shape a real workspace template carries (claude-code / hermes / codex all
// look like this): a providers registry and runtime_config that exist ONLY in
// the template.
const templateConfigYAML = `
name: SEO Agent
template_schema_version: 1
runtime: claude-code
tier: 3
providers:
  - name: anthropic
    base_url: https://api.anthropic.com
  - name: platform
    base_url: https://api.moleculesai.app
models:
  - id: anthropic/claude-opus-4-7
    label: Opus
  - id: minimax/MiniMax-M2.7
    label: MiniMax
env:
  SEO_MODE: audit
runtime_config:
  permission_mode: acceptEdits
skills:
  - seo-all
`

// What ensureDefaultConfig produces from the org node today.
const generatedConfigYAML = `
name: SEO
runtime: claude-code
model: minimax/MiniMax-M2.7
tier: 4
`

func parseYAML(t *testing.T, b []byte) map[string]any {
	t.Helper()
	var m map[string]any
	if err := yaml.Unmarshal(b, &m); err != nil {
		t.Fatalf("unmarshal: %v\n%s", err, b)
	}
	return m
}

// THE DONE CONDITION.
func TestTemplateBase_DeliversProvidersAndModels(t *testing.T) {
	merged, err := mergeTemplateConfigBase([]byte(templateConfigYAML), []byte(generatedConfigYAML))
	if err != nil {
		t.Fatal(err)
	}
	got := parseYAML(t, merged)

	providers, ok := got["providers"].([]any)
	if !ok || len(providers) != 2 {
		t.Fatalf("providers registry did not survive the merge: %#v", got["providers"])
	}
	models, ok := got["models"].([]any)
	if !ok || len(models) != 2 {
		t.Fatalf("models[] did not survive the merge: %#v", got["models"])
	}
	// Other template-only keys survive too — they are equally invisible to a
	// generated config.
	for _, k := range []string{"env", "runtime_config", "skills", "template_schema_version"} {
		if _, present := got[k]; !present {
			t.Errorf("template-only key %q was dropped", k)
		}
	}
}

// The org node owns identity and sizing.
func TestTemplateBase_NodeWinsOnItsOwnFields(t *testing.T) {
	got := parseYAML(t, mustMerge(t, templateConfigYAML, generatedConfigYAML))
	if got["name"] != "SEO" {
		t.Errorf("name = %v; the ORG NODE names the workspace, not the template catalog entry", got["name"])
	}
	if got["tier"] != 4 {
		t.Errorf("tier = %v, want the node's 4 (template said 3)", got["tier"])
	}
	if got["model"] != "minimax/MiniMax-M2.7" {
		t.Errorf("model = %v, want the node's", got["model"])
	}
}

// A template must never re-pin the model. An empty generated model is a visible
// not_configured; inheriting one silently substitutes somebody else's choice.
func TestTemplateBase_TemplateCannotSupplyAModel(t *testing.T) {
	tmpl := templateConfigYAML + "\nmodel: anthropic/claude-opus-4-7\nprovider: anthropic\n"
	got := parseYAML(t, mustMerge(t, tmpl, "name: SEO\nruntime: claude-code\nmodel: \"\"\ntier: 3\n"))

	if m, present := got["model"]; present && m != "" {
		t.Errorf("template re-pinned the model to %v — forbidden by the SSOT-inheritance rule", m)
	}
	if p, present := got["provider"]; present {
		t.Errorf("template supplied provider=%v — also forbidden", p)
	}
}

// "The node did not say" must not erase a template value.
func TestTemplateBase_EmptyGeneratedValueDoesNotEraseTheTemplate(t *testing.T) {
	got := parseYAML(t, mustMerge(t, templateConfigYAML, "name: SEO\nruntime: \"\"\ntier: 3\n"))
	if got["runtime"] != "claude-code" {
		t.Errorf("runtime = %v; an empty generated value means 'unset', not 'set to empty'", got["runtime"])
	}
}

// A zero number IS a choice — treating it as absent would silently promote the
// template's value.
func TestTemplateBase_ZeroIsAValueNotAnAbsence(t *testing.T) {
	got := parseYAML(t, mustMerge(t, templateConfigYAML, "name: SEO\ntier: 0\n"))
	if got["tier"] != 0 {
		t.Errorf("tier = %v, want the node's explicit 0 (template said 3)", got["tier"])
	}
}

// FIX 2's safety property, at the data level: with no template to inherit, the
// generated bytes come back UNCHANGED — not re-marshalled, not reordered.
func TestTemplateBase_NoTemplateReturnsGeneratedBytesVerbatim(t *testing.T) {
	gen := []byte(generatedConfigYAML)
	for _, empty := range []string{"", "# just a comment\n", "null\n"} {
		out, err := mergeTemplateConfigBase([]byte(empty), gen)
		if err != nil {
			t.Fatalf("%q: %v", empty, err)
		}
		if string(out) != string(gen) {
			t.Errorf("%q: generated bytes were rewritten:\n%s", empty, out)
		}
	}
}

// Shallow by design: a half-merged provider registry is worse to debug than a
// wholly-replaced one.
func TestTemplateBase_MergeIsShallow(t *testing.T) {
	got := parseYAML(t, mustMerge(t, templateConfigYAML,
		"name: SEO\nruntime_config:\n  permission_mode: plan\n"))
	rc, ok := got["runtime_config"].(map[string]any)
	if !ok {
		t.Fatalf("runtime_config shape: %#v", got["runtime_config"])
	}
	if rc["permission_mode"] != "plan" {
		t.Errorf("permission_mode = %v, want the node's", rc["permission_mode"])
	}
	if len(rc) != 1 {
		t.Errorf("runtime_config should be REPLACED wholesale, not interleaved: %#v", rc)
	}
}

func TestTemplateBase_MalformedInputIsAnErrorNotACorruptMerge(t *testing.T) {
	if _, err := mergeTemplateConfigBase([]byte("providers: [unclosed"), []byte(generatedConfigYAML)); err == nil {
		t.Error("a malformed template config must error, not silently drop keys")
	}
	if _, err := mergeTemplateConfigBase([]byte(templateConfigYAML), []byte("name: [unclosed")); err == nil {
		t.Error("a malformed generated config must error")
	}
}

func mustMerge(t *testing.T, tmpl, gen string) []byte {
	t.Helper()
	out, err := mergeTemplateConfigBase([]byte(tmpl), []byte(gen))
	if err != nil {
		t.Fatal(err)
	}
	return out
}
