-- Add a monotonic `seq` tiebreaker to activity_logs to make the poll-mode
-- since_id activity feed (#2339) deterministically ordered.
--
-- ROOT CAUSE this fixes: the feed orders by created_at ASC/DESC with NO
-- tiebreaker, and activity_logs.id is a random gen_random_uuid() — there is
-- no monotonic column to break ties. Two rows inserted in the same
-- microsecond (back-to-back A2A logging) share a created_at and come back in
-- arbitrary planner order, so the E2E intermittently sees
-- hello-from-e2e-3 before hello-from-e2e-2. Not a flake — a missing
-- tiebreaker. (Second, related bug fixed in the handler: the since_id cursor
-- filtered `created_at > cursor` strictly, silently dropping a row written in
-- the same microsecond as the cursor row. The composite key below lets the
-- handler compare the full (created_at, seq) tuple.)
--
-- `seq` is a GENERATED BY DEFAULT AS IDENTITY BIGINT — a UNIQUE,
-- monotonic-once-assigned tiebreaker. Precisely (verified on PostgreSQL
-- 16.13, the prod version):
--   * Backfill: adding the IDENTITY column to a populated table REWRITES the
--     table and assigns `seq` to every EXISTING row during the ALTER, in
--     PHYSICAL TABLE-SCAN order (NOT NULL — existing rows do get a value).
--     That order is not guaranteed to equal historical insertion order.
--   * The identity sequence then advances ABOVE max(seq), so every subsequent
--     INSERT that omits `seq` gets a fresh value strictly greater than the
--     backfilled max — collision-free with the backfilled rows.
--   * GENERATED BY DEFAULT (not ALWAYS) so existing INSERTs that don't name
--     `seq` keep working and a caller may still override it if ever needed.
--
-- What `seq` is NOT, and why that's fine:
--   * NOT guaranteed gap-free — rolled-back transactions burn sequence values.
--   * NOT a strict commit-order guarantee under concurrency — two concurrent
--     INSERTs may commit in the opposite order to the `seq` values they drew.
-- Neither property is needed. The feed only requires a TOTAL, STABLE
-- tiebreaker so that (created_at, seq) is a deterministic order: for any two
-- rows it always sorts them the same way and never ties. `seq` being unique
-- and non-null on every row delivers exactly that. Same-created_at rows were
-- returned in ARBITRARY order before this migration; afterward they have a
-- fixed, repeatable order — strictly better, never worse. New traffic is fully
-- deterministic; the backfill makes historical rows deterministic too.
--
-- Idempotent: ADD COLUMN IF NOT EXISTS + CREATE INDEX IF NOT EXISTS so the
-- boot-time runner (and the CI migrate-replay step) can re-apply this safely.

ALTER TABLE activity_logs
    ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Composite index supporting the feed query: WHERE workspace_id = $1
-- AND created_at <cmp> $t ORDER BY created_at, seq. The (workspace_id,
-- created_at, seq) prefix serves both the ASC cursor path and the DESC recent
-- path (Postgres reads the same btree backwards for DESC). This is distinct
-- from migration 009's idx_activity_ws_type_time (workspace_id, activity_type,
-- created_at) — that one is type-prefixed and can't drive a type-agnostic feed
-- scan — and from 048's per-peer source_id/target_id indexes.
CREATE INDEX IF NOT EXISTS idx_activity_ws_created_seq
    ON activity_logs (workspace_id, created_at, seq);
